# today we will discuss about build in funtions 
print("Hello")
a=int(input("Enter the number:"))
print(a)
print(type(a))
print(abs(-8))
print(pow(1,89))
print(min("jkiagf"))
print(max(98,6))
print(round(897.9897986))
print(divmod(5,2))
print(round(8.9898))
print(id(8))